commannds:
  # Hora
  - command:
      input: Que Horas são?
      entity: time
      action: getTime
  - command:
      input: Me diga as horas.
      entity: time
      action: getTime
  # Data
  - command:
      input: Qual é a data de hoje?
      entity: time
      action: getDate
  - command:
      input: Que dia é hoje.
      entity: time
      action: getDate
   # Tempo
  - command:
      input: Previsão do tempo
      entity: time
      action: getWeather
  - command:
      input: Como está o clima
      entity: time
      action: getWeather
  # Open
  - command:
      input: Abrir google
      entity: open
      action:
  - command:
      input: Abrir youtube
      entity: open
      action: